---
title: Dose-response analysis of C-to-T reporter (CA044)
author: "Soh Ishiguro"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    toc_float: FALSE
    toc_depth: 3
    toc_collapsed: FALSE
    number_sections: yes
    keep_md: yes
    fig_caption: yes
  pdf_document: default
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  comment = "#>",
  out.width = "50%",
  dpi = 300
)
```

Experimental ID: CA044 (Flow was done by Oct 18 2018).   
Original data file path: `https://www.dropbox.com/sh/t9ys3askybwoqde/AABAQ4asZBjUTRcdH1HfL8vua?dl=0`

```{r}
library(RColorBrewer)
library(ggplot2)
library(ggridges)
library(ggforce)
library(dplyr)
library(scales)
library(data.table)
library(rmarkdown)
library(openCyto)
library(flowWorkspace)
library(CytoExploreR)
```
```{r}
# loading FCSs
cytoset <- load_cytoset_from_fcs(path = "./fcs")
gs <- GatingSet(cytoset)

# Transformation
trans.log <- cyto_transformer_log(gs, channels = c("FITC-A"), plot = FALSE)
gs.trans <- cyto_transform(gs, trans = trans.log, plot = FALSE)
```

```{r}
cyto_details(gs.trans)$exp_id <- "CA044"
cyto_details(gs.trans)$dose_str <- c(
  rep("0ng", 6), rep("100ng", 6), rep("200ng", 6),
  rep("400ng", 6), rep("50ng", 6), rep("600ng", 6),
  rep("800ng", 6)
)
cyto_details(gs.trans)$dose_ng <- c(
  rep(0, 6), rep(100, 6), rep(200, 6),
  rep(400, 6), rep(50, 6), rep(600, 6),
  rep(800, 6)
)
cyto_details(gs.trans)$OT <- rep(c("NC", "PC"), 21)
cyto_details(gs.trans)$barcode <- rep(c("BC2", "BC2", "BC4", "BC4", "BC6", "BC6"), 7)
cyto_details(gs.trans) %>% paged_table()
```

Create manual gates.
```{r, eval=FALSE}
cyto_gate_draw(
  gs.trans,
  parent = "root", alias = "P1",
  channels = c("FSC-A", "SSC-A"),
  gatingTemplate = "CA044_manual_gates.csv",
  xlim = c(-10, 1 * 10^6),
  ylim = c(-10, 1 * 10^6),
  type = "polygon"
)
```

```{r, eval=FALSE}
cyto_gate_draw(
  gs.trans["0ng_BC2_NC.fcs"],
  parent = "P1",
  alias = "GFP",
  channels = c("FITC-A", "FSC-A"),
  gatingTemplate = "CA044_manual_gates.csv",
  xlim = c(-10, 1 * 10^7),
  ylim = c(-10, 1 * 10^6),
  type = "interval"
)
```

```{r}
gt <- gatingTemplate("CA044_manual_gates.csv")
gt_gating(gt, gs.trans)
# gs_pop_remove("GFP", gs = gs.trans)
```

```{r}
stat <- flowWorkspace::gs_pop_get_stats(gs.trans, "GFP", type = "percent")
sample.meta <- cyto_details(gs.trans)
stat.merged.df <- merge(stat, sample.meta, by.x = "sample", by.y = "name")
```

```{r, eval=FALSE}
# save_gs(gs.trans, path = "./gs_trans")
load_gs("./gs_trans", verbose = TRUE)
```

```{r line_plt, fig.width=3, fig.height=2}
FONT.SIZE <- 7
LABEL.FONT.SIZE <- 7
LINE.W <- 0.232 # 0.5pt
DATE <- "04192022"

g.line.plt <- ggplot(
  stat.merged.df %>% dplyr::filter(OT == "PC"),
  aes(
    x = as.numeric(dose_ng),
    y = percent, colour = barcode, group = barcode
  )
) +
  geom_line(alpha = 0.4) +
  geom_point(size = 1.7) +
  scale_x_continuous(expand = c(0.05, 0.01), limits = c(0, 800)) +
  scale_y_continuous(
    limits = c(0, 0.3), expand = c(0.01, 0),
    labels = scales::percent_format(suffix = "")
  ) +
  labs(x = "Input DNA (ng)", y = "%EGFP positive cells") +
  scale_colour_brewer(palette = "Set1") +
  theme_classic() +
  theme(
    strip.background = element_blank(),
    plot.background = element_blank(),
    panel.background = element_blank(),
    axis.title = element_text(colour = "black", size = FONT.SIZE),
    axis.ticks = element_line(colour = "black", size = LINE.W),
    axis.line = element_line(colour = "black", size = LINE.W),
    axis.text = element_text(colour = "black", size = LABEL.FONT.SIZE)
  )
g.line.plt

ggsave(plot = g.line.plt + guides(colour = "none"), filename = sprintf("plots/GFP_line_%s.pdf", DATE), w = 1.5, h = 2.0, device = cairo_pdf)
```

Export single-cell event to csv file.
```{r}
sample.names <- sampleNames(gs.trans)
gs.exp.df <- data.table()
for (sample in sample.names) {
  message(sprintf("Processing: %s", sample))
  df <- gs_get_singlecell_expression(gs.trans, c("P1"),
    threshold = FALSE, marginal = FALSE, inverse.transform = TRUE,
    other.markers = c("SSC-A", "FSC-A", "FITC-A")
  )[[sample]] %>%
    data.table() %>%
    mutate(sample = sample)
  gs.exp.df <- rbindlist(list(gs.exp.df, df))
}
exp.df <- merge(gs.exp.df, sample.meta, by.x = "sample", by.y = "name")
```
```{r}
write.csv(sample.meta, quote = FALSE, row.names = FALSE, file = "./processed_csv/sample_meta_CA044.csv")
write.csv(exp.df, quote = FALSE, row.names = FALSE, file = "./processed_csv/single_cell_events_CA044.csv")
```

Make a layered histogram to see distribution changes.
```{r fig_hist, fig.width=4.7, fig.height=2.4}
exported_file <- "./processed_csv/single_cell_events_CA044.csv"
df <- fread(exported_file, header = TRUE, sep = ",")

inv.log.trans <- function(x) {
  ts <- flowWorkspace::flowjo_log_trans()
  inv <- ts[["inverse"]](x)
  return(inv)
}

GFP.gate <- gt@edgeData@data[["/P1|/P1/GFP"]]$gtMethod@args$gate@.Data$`Combined Events`@.Data[[1]]
GFP.cutoff <- GFP.gate@min[["FITC-A"]] %>% inv.log.trans()

# rename barcode name
supp.labs <- c("BC-C1", "BC-C2", "BC-C3")
names(supp.labs) <- c("BC2", "BC4", "BC6")

plt.hist <- function(data) {
  g <- ggplot(data, aes(y = dose_str, x = `FITC-A`, fill = stat(x))) +
    facet_wrap(~barcode, labeller = as_labeller(supp.labs)) +
    geom_density_ridges_gradient(
      na.rm = TRUE,
      colour = "gray90", scale = 2.5, quantile_lines = FALSE,
      quantiles = 2, vline_size = LINE.W, vline_color = "gray", size = 0.2
    ) +
    scale_fill_gradientn(limits = c(0, 5), colours = c("black", "gray10", "green2", "green2", "greenyellow")) +
    geom_vline(xintercept = GFP.cutoff, linetype = "dashed", size = LINE.W, colour = "gray20") +
    scale_x_log10(
      breaks = c(10^0, 10^2, 10^4),
      labels = scales::trans_format("log10", math_format(10^.x)),
      expand = c(0, 0),
      limits = c(0.5, 10^5)
    ) +
    scale_y_discrete(expand = c(0, 0)) +
    labs(x = "EGFP intensity (a.u.)", y = "") +
    theme_classic() +
    theme(
      panel.background = element_blank(),
      plot.background = element_blank(),
      panel.spacing.y = unit(0.5, "lines"),
      panel.spacing.x = unit(0.8, "lines"),
      axis.line.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.ticks.x = element_line(colour = "black", size = LINE.W),
      axis.line = element_line(size = LINE.W),
      axis.title = element_text(size = FONT.SIZE),
      axis.text.x = element_text(colour = "black", size = LABEL.FONT.SIZE),
      axis.text.y = element_text(colour = "black", size = LABEL.FONT.SIZE),
      strip.text.x = element_text(colour = "black", size = LABEL.FONT.SIZE),
      strip.background = element_blank()
    )
  return(g)
}

# Reorder with proper order
df$dose_str <- factor(df$dose_str, levels = c("0ng", "50ng", "100ng", "200ng", "400ng", "600ng", "800ng"))
g.hist <- plt.hist(df %>% dplyr::filter(.data[["FITC-A"]] > 1))
ggsave(plot = g.hist + guides(fill = "none"), filename = sprintf("GFP_hist_%s.pdf", DATE), w = 3.5, h = 2.8, device = cairo_pdf)
```
